In [1]:
import pandas as pd

In [2]:
new = pd.read_csv("kc_house_data.csv")

In [3]:
new

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [4]:
new.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [5]:
import h2o
from h2o.automl import H2OAutoML

In [6]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: java version "20.0.1" 2023-04-18; Java(TM) SE Runtime Environment (build 20.0.1+9-29); Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
  Starting server from /Users/lakshmiph/anaconda3/lib/python3.10/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /var/folders/dx/lsnc36057kg9y4kq_ssgm6_h0000gn/T/tmpbo48smr5
  JVM stdout: /var/folders/dx/lsnc36057kg9y4kq_ssgm6_h0000gn/T/tmpbo48smr5/h2o_lakshmiph_started_from_python.out
  JVM stderr: /var/folders/dx/lsnc36057kg9y4kq_ssgm6_h0000gn/T/tmpbo48smr5/h2o_lakshmiph_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  --------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Europe/London
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.42.0.1
H2O_cluster_version_age:    1 month
H2O_cluster_name:           H2O_from_python_lakshmiph_822sg8
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.9 final
--------------------------  --------------------------------

In [7]:
# convert pandas DataFrame into H2O Frame
new_df = h2o.H2OFrame(new)
# Describe  the train h20Frame
new_df.describe()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

Rows:21613
Cols:21

         id                  date             price               bedrooms           bathrooms           sqft_living        sqft_lot           floors              waterfront            view                 condition           grade               sqft_above          sqft_basement       yr_built            yr_renovated        zipcode            lat                  long                 sqft_living15       sqft_lot15
-------  ------------------  ---------------  ------------------  -----------------  ------------------  -----------------  -----------------  ------------------  --------------------  -------------------  ------------------  ------------------  ------------------  ------------------  ------------------  ------------------  -----------------  -------------------  -------------------  ------------------  ------------------
type     int                 enum             int                 int                real                int                int                real                int                   int                  int                 int                 int                 int                 int                 int                 int                real                 real                 int                 int
mins     1000102.0                            75000.0             0.0                0.0                 290.0              520.0              1.0                 0.0                   0.0                  1.0                 1.0                 290.0               0.0                 1900.0              0.0                 98001.0            47.1559              -122.519             399.0               651.0
mean     4580301520.864987                    540088.1417665284   3.370841623097218  2.114757321982139   2079.899736269819  15106.96756581695  1.4943089807060526  0.007541757275713691  0.23430342849211097  3.4094295100171164  7.6568731781798105  1788.3906907879518  291.50904548188555  1971.0051357979064  84.4022579003377    98077.93980474674  47.56005251931665    -122.21389640494158  1986.5524915560036  12768.45565169118
maxs     9900000190.0                         7700000.0           33.0               8.0                 13540.0            1651359.0          3.5                 1.0                   4.0                  5.0                 13.0                9410.0              4820.0              2015.0              2015.0              98199.0            47.7776              -121.315             6210.0              871200.0
sigma    2876565571.3120522                   367127.19648270035  0.930061831147451  0.7701631572177408  918.4408970468095  41420.51151513551  0.5399888951423489  0.08651719772788766   0.7663175692736117   0.6507430463662044  1.1754587569743344  828.0909776519175   442.57504267746685  29.373410802386235  401.67924001917555  53.50502625747248  0.13856371024192365  0.14082834238139275  685.3913042527788   27304.179631338524
zeros    0                                    0                   13                 10                  0                  0                  0                   21450                 19489                0                   0                   0                   13126               0                   20699               0                  0                    0                    0                   0
missing  0                   0                0                   0                  0                   0                  0                  0                   0                     0                    0                   0                   0                   0                   0                   0                   0                  0                    0                    0                   0
0        7129300520.0        20141013T000000  221900.0            3.0                1.0                 1180.0             5650.0             1.0                 0.0                   0.0                  3.0                 7.0                 1180.0              0.0                 1955.0              0.0                 98178.0            47.5112              -122.257             1340.0              5650.0
1        6414100192.0        20141209T000000  538000.0            3.0                2.25                2570.0             7242.0             2.0                 0.0                   0.0                  3.0                 7.0                 2170.0              400.0               1951.0              1991.0              98125.0            47.721               -122.319             1690.0              7639.0
2        5631500400.0        20150225T000000  180000.0            2.0                1.0                 770.0              10000.0            1.0                 0.0                   0.0                  3.0                 6.0                 770.0               0.0                 1933.0              0.0                 98028.0            47.7379              -122.233             2720.0              8062.0
3        2487200875.0        20141209T000000  604000.0            4.0                3.0                 1960.0             5000.0             1.0                 0.0                   0.0                  5.0                 7.0                 1050.0              910.0               1965.0              0.0                 98136.0            47.5208              -122.393             1360.0              5000.0
4        1954400510.0        20150218T000000  510000.0            3.0                2.0                 1680.0             8080.0             1.0                 0.0                   0.0                  3.0                 8.0                 1680.0              0.0                 1987.0              0.0                 98074.0            47.6168              -122.045             1800.0              7503.0
5        7237550310.0        20140512T000000  1225000.0           4.0                4.5                 5420.0             101930.0           1.0                 0.0                   0.0                  3.0                 11.0                3890.0              1530.0              2001.0              0.0                 98053.0            47.6561              -122.005             4760.0              101930.0
6        1321400060.0        20140627T000000  257500.0            3.0                2.25                1715.0             6819.0             2.0                 0.0                   0.0                  3.0                 7.0                 1715.0              0.0                 1995.0              0.0                 98003.0            47.3097              -122.327             2238.0              6819.0
7        2008000270.0        20150115T000000  291850.0            3.0                1.5                 1060.0             9711.0             1.0                 0.0                   0.0                  3.0                 7.0                 1060.0              0.0                 1963.0              0.0                 98198.0            47.4095              -122.315             1650.0              9711.0
8        2414600126.0        20150415T000000  229500.0            3.0                1.0                 1780.0             7470.0             1.0                 0.0                   0.0                  3.0                 7.0                 1050.0              730.0               1960.0              0.0                 98146.0            47.5123              -122.337             1780.0              8113.0
9        3793500160.0        20150312T000000  323000.0            3.0                2.5                 1890.0             6560.0             2.0                 0.0                   0.0                  3.0                 7.0                 1890.0              0.0                 2003.0              0.0                 98038.0            47.3684              -122.031             2390.0              7570.0
[21613 rows x 21 columns]

In [8]:
y = "price"
x = new_df.columns
# remove label classvariable from feature variable
x.remove(y)

In [9]:
splits = new_df.split_frame(ratios = [0.8], seed = 1)
train = splits[0]
test = splits[1]

In [ ]:

aml = H2OAutoML(max_models=50, seed = 1, project_name = "house_prices")
aml.train(x = x, y = y, training_frame = train, validation_frame=test)

AutoML progress: |
19:05:16.807: User specified a validation frame with cross-validation still enabled. Please note that the models will still be validated using cross-validation only, the validation frame will be used to provide purely informative validation metrics on the trained models.
19:05:16.813: AutoML: XGBoost is not available; skipping it.

██████████████████████████████████████████████████████████████