In [1]:
import pandas as pd

In [2]:
new = pd.read_csv("uber.csv")

In [3]:
new

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5
...,...,...,...,...,...,...,...,...,...
199995,42598914,2012-10-28 10:49:00.00000053,3.0,2012-10-28 10:49:00 UTC,-73.987042,40.739367,-73.986525,40.740297,1
199996,16382965,2014-03-14 01:09:00.0000008,7.5,2014-03-14 01:09:00 UTC,-73.984722,40.736837,-74.006672,40.739620,1
199997,27804658,2009-06-29 00:42:00.00000078,30.9,2009-06-29 00:42:00 UTC,-73.986017,40.756487,-73.858957,40.692588,2
199998,20259894,2015-05-20 14:56:25.0000004,14.5,2015-05-20 14:56:25 UTC,-73.997124,40.725452,-73.983215,40.695415,1
199999,11951496,2010-05-15 04:08:00.00000076,14.1,2010-05-15 04:08:00 UTC,-73.984395,40.720077,-73.985508,40.768793,1

In [4]:
new.isnull().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [4]:
import h2o
from h2o.automl import H2OAutoML

In [5]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  --------------------------------
H2O_cluster_uptime:         3 hours 19 mins
H2O_cluster_timezone:       Europe/London
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.42.0.1
H2O_cluster_version_age:    1 month
H2O_cluster_name:           H2O_from_python_lakshmiph_822sg8
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.873 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.9 final
--------------------------  --------------------------------

In [6]:
# convert pandas DataFrame into H2O Frame
new_df = h2o.H2OFrame(new)
# Describe  the train h20Frame
new_df.describe()

Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| (done) 100%

Rows:200000
Cols:9

         Unnamed: 0          key                  fare_amount         pickup_datetime          pickup_longitude    pickup_latitude     dropoff_longitude    dropoff_latitude    passenger_count
-------  ------------------  -------------------  ------------------  -----------------------  ------------------  ------------------  -------------------  ------------------  ------------------
type     int                 time                 real                string                   real                real                real                 real                int
mins     1.0                 1230772522000.0      -52.0               NaN                      -1340.64841         -74.01551500000001  -3356.6663           -881.9855130000001  0.0
mean     27712503.68234996   1332428538433.1194   11.359955249999976  NaN                      -72.52763791623696  39.93588537801236   -72.52529162747385   39.92389040183269   1.6845350000000012
maxs     55423567.0          1435707639000.0      499.0               NaN                      57.418457           1644.421482         1153.5726029999998   872.6976279999999   208.0
sigma    16013822.212829232  58223095246.75381    9.9017762250699     NaN                      11.437787338931727  7.720539407361824   13.117407778536665   6.794828840545099   1.3859965507558802
zeros    0                   0                    5                   0                        3786                3782                3764                 3758                709
missing  0                   0                    0                   0                        0                   0                   1                    1                   0
0        24238194.0          2015-05-07 19:52:06  7.5                 2015-05-07 19:52:06 UTC  -73.99981689453125  40.73835372924805   -73.99951171875      40.72321701049805   1.0
1        27835199.0          2009-07-17 20:04:56  7.7                 2009-07-17 20:04:56 UTC  -73.994355          40.728225           -73.99471            40.750325           1.0
2        44984355.0          2009-08-24 21:45:00  12.9                2009-08-24 21:45:00 UTC  -74.005043          40.74077            -73.962565           40.772647           1.0
3        25894730.0          2009-06-26 08:22:21  5.3                 2009-06-26 08:22:21 UTC  -73.976124          40.790844           -73.965316           40.803349           3.0
4        17610152.0          2014-08-28 17:47:00  16.0                2014-08-28 17:47:00 UTC  -73.925023          40.744085           -73.97308199999999   40.761247           5.0
5        44470845.0          2011-02-12 02:27:09  4.9                 2011-02-12 02:27:09 UTC  -73.96901899999999  40.75591            -73.96901899999999   40.75591            1.0
6        48725865.0          2014-10-12 07:04:00  24.5                2014-10-12 07:04:00 UTC  -73.96144699999999  40.693965000000006  -73.871195           40.774297           5.0
7        44195482.0          2012-12-11 13:52:00  2.5                 2012-12-11 13:52:00 UTC  0.0                 0.0                 0.0                  0.0                 1.0
8        15822268.0          2012-02-17 09:32:00  9.7                 2012-02-17 09:32:00 UTC  -73.975187          40.745767           -74.00272            40.743537           1.0
9        50611056.0          2012-03-29 19:06:00  12.5                2012-03-29 19:06:00 UTC  -74.001065          40.741787           -73.96304            40.775012           1.0
[200000 rows x 9 columns]

In [7]:
y = "fare_amount"
x = new_df.columns
# remove label classvariable from feature variable
x.remove(y)

In [8]:
splits = new_df.split_frame(ratios = [0.8], seed = 1)
train = splits[0]
test = splits[1]

In [9]:
aml = H2OAutoML(max_models=50, seed = 1)
aml.train(x = x, y = y, training_frame = train, validation_frame=test)

AutoML progress: |
22:24:26.244: User specified a validation frame with cross-validation still enabled. Please note that the models will still be validated using cross-validation only, the validation frame will be used to provide purely informative validation metrics on the trained models.
22:24:26.244: AutoML: XGBoost is not available; skipping it.
22:24:26.245: _train param, Dropping bad and constant columns: [pickup_datetime]


22:24:26.817: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
22:24:37.332: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆ
22:24:46.653: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆ
22:24:52.433: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆ
22:24:58.841: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆ
22:25:07.464: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆâ–ˆ
22:25:20.265: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆ
22:25:25.715: _train param, Dropping bad and constant columns: [pickup_datetime]

â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
23:51:13.404: _train param, Dropping unused columns: [pickup_datetime]


23:51:15.799: _train param, Dropping unused columns: [pickup_datetime]

| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_1_AutoML_20_20230720_222426


Model Summary for Stacked Ensemble:
key                                        value
-----------------------------------------  ----------------
Stacking strategy                          cross_validation
Number of base models (used / total)       4/82
# GBM base models (used / total)           4/55
# DRF base models (used / total)           0/2
# DeepLearning base models (used / total)  0/24
# GLM base models (used / total)           0/1
Metalearner algorithm                      GLM
Metalearner fold assignment scheme         Random
Metalearner nfolds                         5
Metalearner fold_column
Custom metalearner hyperparameters         None

ModelMetricsRegressionGLM: stackedensemble
** Reported on train data. **

MSE: 15.450113916977513
RMSE: 3.9306632922418467
MAE: 2.1390066311523777
RMSLE: 0.2643787014070195
Mean Residual Deviance: 15.450113916977513
R^2: 0.8432307432739228
Null degrees of freedom: 9990
Residual degrees of freedom: 9986
Null deviance: 984670.0753625414
Residual deviance: 154362.08814452233
AIC: 55716.754988943765

ModelMetricsRegressionGLM: stackedensemble
** Reported on validation data. **

MSE: 25.890955616798024
RMSE: 5.088315597208768
MAE: 2.6117283201202266
RMSLE: NaN
Mean Residual Deviance: 25.890955616798024
R^2: 0.7436635260894832
Null degrees of freedom: 39981
Residual degrees of freedom: 39977
Null deviance: 4038593.892896034
Residual deviance: 1035172.1874708186
AIC: 243573.1789319092

ModelMetricsRegressionGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 25.32099532503575
RMSE: 5.031997150738039
MAE: 2.548154157463026
RMSLE: NaN
Mean Residual Deviance: 25.32099532503575
R^2: 0.7397744199635388
Null degrees of freedom: 160017
Residual degrees of freedom: 160013
Null deviance: 15570877.528359644
Residual deviance: 4051815.029921571
AIC: 971243.0068372287

Cross-Validation Metrics Summary:
                        mean         sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  -----------  ---------  ------------  ------------  ------------  ------------  ------------
mae                     2.55168      0.0195252  2.57325       2.54649       2.52608       2.56923       2.54336
mean_residual_deviance  25.3197      2.94895    24.9772       26.5303       22.3832       23.0044       29.7036
mse                     25.3197      2.94895    24.9772       26.5303       22.3832       23.0044       29.7036
null_deviance           3.11418e+06  60052.3    3.20023e+06   3.07154e+06   3.07828e+06   3.06634e+06   3.15449e+06
r2                      0.73993      0.0281164  0.750024      0.723809      0.765518      0.761411      0.698891
residual_deviance       810240       93594      799945        848308        721790        731447        949712
rmse                    5.02519      0.289812   4.99772       5.15076       4.73109       4.79629       5.4501
rmsle                   nan          0          nan           nan           nan           nan           nan

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.